#!/usr/bin/env bash
set -eu -o pipefail

##
# Get your new GS&F workspace set up
##

# If there is any cleanup to do on an exit, do it here.
cleanup() {
	rm "$1"
}

releaseURL() {
    curl -L --silent 'https://api.github.com/repos/gsandf/new-dev-setup/releases/latest' \
    | grep 'browser_download_url' \
    | grep -o 'https:.*' \
    | tr -d '"'
}

main() {
    tempFile=$(mktemp 'setup.XXXX')
    trap "cleanup ${tempFile}" EXIT

    curl -L --silent $(releaseURL) -o $tempFile
    chmod +x $tempFile
    ./$tempFile
}

main
